---
title: ""
output: html_document
---
<br>

## **Lessons**

[All lessons provided by NCEAS and collaborators here on GitHub.](https://github.com/NCEAS/oss-lessons)

<br>

## **Lessons by Day**

<br>

### Day 1: Mon Jul 10
- [Course Overview](https://nceas.github.io/oss-lessons/course-overview/course-overview.html#/)
- [Networks and Servers](https://nceas.github.io/oss-lessons/servers-networks-command-line/1-servers-net.html)
- [Unix Command Line](https://nceas.github.io/oss-lessons/servers-networks-command-line/2-commandline-intro.html)
- [Thinking Preferences](https://nceas.github.io/oss-lessons/thinking-preferences/thinking-preferences.html#/)
- [R Markdown and R studio](https://github.com/NCEAS/oss-lessons/blob/gh-pages/rmarkdown-rstudio/rmarkdown-rstudio.Rmd)

### Day 2: Tue Jul 11
- [Version control: git basics](https://nceas.github.io/oss-lessons/version-control/1-git-basics.html)
- [Version control: remote collaboration with git and GitHub](https://nceas.github.io/oss-lessons/version-control/2-git-remote-collaboration.html)
- [Version control: branches and merge conflicts](https://nceas.github.io/oss-lessons/version-control/3-git-advanced.html)
- [Version control: Rstudio and git](https://nceas.github.io/oss-lessons/version-control/4-getting-started-with-git-in-RStudio.html)
- [The message box](https://nceas.github.io/oss-lessons/message-box/message-box.html#/)

### Day 3: Wed Jul 12
- [Unix tools](https://nceas.github.io/oss-lessons/servers-networks-command-line/2-commandline-intro.html)
- [Bash shell scripts](https://nceas.github.io/oss-lessons/servers-networks-command-line/3-bash-loops.html)
- [R Review & Assessment](https://nceas.github.io/oss-lessons/r-review-and-assessment/r-review-and-assessment.html)
- [Data management and repositories](https://nceas.github.io/oss-lessons/data-repositories/data-repositories.html)
- [Data publishing](https://nceas.github.io/oss-lessons/publishing-data/upload-data.html)

### Day 4: Thu Jul 13
- [Ecological metadata](https://nceas.github.io/oss-lessons/ecological-metadata/ecological-metadata.html)
- [Open data](https://nceas.github.io/oss-lessons/open-data-in-r/open-data-in-R.html)
- [Data liberation - Web scraping](https://nceas.github.io/oss-lessons/data-liberation/intro-webscraping.html)
- [Data liberation - Text mining](https://nceas.github.io/oss-lessons/data-liberation/intro-text-mining.html)
- [Regular expressions](https://nceas.github.io/oss-lessons/regular-expressions/regular-expressions.html)

### Day 5: Fri Jul 14
- Collaboration
- [Facilitation techniques](https://nceas.github.io/oss-lessons/meeting-facilitation/meeting-facilitation.html#/)
- [Data wrangling: Tidyverse](https://nceas.github.io/oss-lessons/data-wrangling/tidyverse.html)
- Data Munging

### Day 6: Mon Jul 17
- [Meta analysis intro](https://nceas.github.io/oss-lessons/meta-analysis/index.html)
- [Meta analysis I](https://nceas.github.io/oss-lessons/meta-analysis/step1.html)
- [Meta analysis II](https://nceas.github.io/oss-lessons/meta-analysis/step2.html)
- [Meta analysis III](https://nceas.github.io/oss-lessons/meta-analysis/step3.html)
- [Meta analysis IV](https://nceas.github.io/oss-lessons/meta-analysis/step4.html)
- [Meta analysis V](https://nceas.github.io/oss-lessons/meta-analysis/step5.html)

### Day 7: Tue Jul 18
- [Good enough data modeling](https://nceas.github.io/oss-lessons/sql-database/01-sql-database-intro.html)
- [Start SQL with PostgresQL](https://nceas.github.io/oss-lessons/sql-database/02-sql-start.html)
- [SQL and database access in R](https://nceas.github.io/oss-lessons/sql-database-access-in-r/sql-database-access-in-r.html)

### Day 8: Wed Jul 19
- [Data wrangling](https://nceas.github.io/oss-lessons/data-munging-qa-qc-cleaning/data-munging-qa-qc-cleaning.html)
- [Creating R Functions](https://nceas.github.io/oss-lessons/creating-r-functions/creating-r-functions.html)
- [Creating R packages](https://nceas.github.io/oss-lessons/creating-r-packages/creating-r-packages.html)
- Testing R code

### Day 9: Thu Jul 20

- [Publishing Data](https://github.com/NCEAS/oss-lessons/tree/gh-pages/publishing-data)
- [Reproducible Papers with RMarkdown](https://nceas.github.io/oss-lessons/reproducible-papers-with-rmd/reproducible-papers-with-rmd.html)


### Day 10: Fri Jul 21
- [Metagenomics](https://nceas.github.io/oss-lessons/metagenomics/)

### Day 11: Mon Jul 24
- GIS and geopspatial concepts
    - [Intro to spatial data concepts](https://nceas.github.io/oss-lessons/spatial-data-gis-law/1-mon-spatial-data-intro.html)
    - [QGIS - an open alternative to ArcGIS](https://nceas.github.io/oss-lessons/spatial-data-gis-law/2-mon-intro-to-open-gis-qgis.html)
    - [Plot & manage raster and vector data in R](https://nceas.github.io/oss-lessons/spatial-data-gis-law/3-mon-intro-gis-in-r.html)
- [Publishing maps to the web in R](https://nceas.github.io/oss-lessons/publishing-maps-to-the-web-in-r/publishing-maps-to-the-web-in-r.html)
- [Publication ready maps in R](https://github.com/NCEAS/oss-lessons/tree/gh-pages/publication-ready-maps-in-r) (R scripts examples)

### Day 12: Tue Jul 25
- [Getting started with spatial analysis in R](https://nceas.github.io/oss-lessons/spatial-data-gis-law/4-tues-spatial-analysis-in-r.html)
- [NetCDF and HDF5](https://nceas.github.io/oss-lessons/spatial-data-gis-law/5-tues-intro-hierarchical-formats.html)

### Day 13: Wed Jul 26
- [Dataviz and Interactive Tools](https://nceas.github.io/oss-lessons/dataviz-and-interactive-tools/dataviz-and-interactive-tools.html)
    - [Submodule: ggplot2](https://nceas.github.io/oss-lessons/dataviz-and-interactive-tools/module-1-ggplot2.html)
    - [Submodule: Shiny](https://nceas.github.io/oss-lessons/dataviz-and-interactive-tools/module-2-shiny.html)
- [Perfunctory Python](https://nceas.github.io/oss-lessons/why-python/python-the-why.html)    

### Day 14: Thu Jul 27
- [Parallel Computing in R](https://nceas.github.io/oss-lessons/parallel-computing-in-r/parallel-computing-in-r.html)
- [Open Science](https://speakerdeck.com/cjlortie/open-science-and-the-spells-that-you-ought-to-know)

### Day 15: Fri Jul 28
- Group Presentations

